name: Build Forge 1.8.9 Mod

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build the Mod
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: Upload Compiled Mod
        uses: actions/upload-artifact@v3
        with:
          name: NoDeathAnimation
          path: build/libs/*.jar
          
